[project]
name = "tsfmproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kage08", email = "harshavardhan864.hk@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "torch>=2.5.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
